
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: ieat
  password: fbs3012
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ieat_dev


test:
  <<: *default
  database: ieat_test

production:
  <<: *default
  database: ieat_production
  username: ieat
  password: <%= ENV['IEAT_DATABASE_PASSWORD'] %>
